site :opscode

cookbook 'curl'
cookbook 'denyhosts'
cookbook 'fail2ban'
cookbook 'git'
cookbook 'htop', :path => 'site-cookbooks/htop'
cookbook 'iftop'
cookbook 'java'
cookbook 'jenkins', :git => 'git@github.com:opscode-cookbooks/jenkins.git'
cookbook 'ntp'
cookbook 'openssh'
cookbook 'rsync'
cookbook 'screen'
cookbook 'sudo'
cookbook 'timezone'
cookbook 'vim'
cookbook 'xslt'
cookbook 'yum'
cookbook 'zlib'
